--- 
branches: 
  only: 
    - src
cache: npm
deploy: 
  fqdn: ~
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: public
  provider: pages
  skip-cleanup: true
  target_branch: master
  true: 
    branch: src
language: node_js
node_js: 
  - 10
script: 
  - "chmod +x ./build.sh"
  - ./build.sh
sudo: false
